Continued with magic string issue
openclams/clams pull request #29
Opened 2020-08-29 09:15 UTC by RobinLaidig

Should be finished now, I went through the whole clams code

2020-09-01 20:01 UTC, matejetz requested changes

2020-09-02 08:56 UTC, RobinLaidig commented
Fixed it now, thanks for the clarification

2020-09-02 15:24 UTC, matejetz commented on src/app/server-dashboard/Servers.ts
>    private readonly defaultServer: string = 'http:\\localhost:80';
i would suggest we follow the [boy scout rule](https://deviq.com/boy-scout-rule/) (here meaning to also rename previously misnamed vars)

2020-09-02 15:25 UTC, matejetz requested changes
minor things, free to be merged after changes are applied

2020-09-02 15:25 UTC, matejetz commented on src/app/app.service.ts
> +  private readonly KEY_PROJECT_DIRECTORY = 'ClamsProjectsDirectory';
this is still missing a type annotation

2020-09-05 16:08 UTC, matejetz commented
nice!

2020-09-05 16:08 UTC, merged